name: CI

on: [push]

jobs:
  lint:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download reshaper
      run: certutil -urlcache -split -f "https://download-cf.jetbrains.com/resharper/ReSharperUltimate.2019.3.1/JetBrains.ReSharper.CommandLineTools.2019.3.1.zip" resharper.zip
    - name: Unzip
      run: tar -xf resharper.zip
    - name: Check linting
      run: dir 11_NTNU_treadmill
      #D:\a\11_NTNU_treadmill\11_NTNU_treadmill\inspectcode.exe --extensions=JetBrains.Unity --output=output.xml 11_NTNU_treadmill\11_NTNU_treadmill.sln
    - name: Print output
      run: type output.xml
    - name: Print output
      run: type output.xml
    - name: Fail if linting not OK
      run: |
        text=open('output.xml', 'r').read()
        for i in ["RedundantUsingDirective", "UnusedType.Global", "CheckNamespace", "UnusedMember.Local", "InconsistentNaming", "NotAccessedVariable.Compiler", "RedundantAssignment", "ConditionIsAlwaysTrueOrFalse", "CSharpWarnings"]:
          if i in text: exit(1)
      shell: python